name: Test GitHub Secret in Docker

on:
  push:
    branches: [main]

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t php-secret-test .

      - name: Run container and pass secret
        run: |
          docker run -e MY_SECRET=${{ secrets.MY_SECRET }} php-secret-test